### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Yadro** [leamsii/Just-Dance-2019-IPK-Unpacker#1]
It doesn't work, I always see `Log: Unpacking 0 files..` error.
I've tried on files from http://justdanceworkshop.boards.net/thread/18/jdworkshopteam-dance-ultimate-2019

**Comment by leamsii** [comment]
Send me the file you're trying to use this with.

**Comment by Yadro** [comment]
I attached smallest size file that I found:
[bundlelogic_pc.zip](https://github.com/leamsii/Just-Dance-2019-IPK-Unpacker/files/3843477/bundlelogic_pc.zip)

**Comment by leamsii** [comment]
Is working for me, make sure to use Python version 3+, I attached the files.

[bundle.zip](https://github.com/leamsii/Just-Dance-2019-IPK-Unpacker/files/3849164/bundle.zip)
